### ISSUE TITLE
Feature - Change the proficiency die(s) used

### ISSUE THREAD

**Issue by caewok** [NekroDarkmoon/optional-rules-dnd5e#11]
**Feature for you to consider**
Allow the GM to change the proficiency die(s) used. You could let people give you min/max levels and die formula used, and they could +/- to add/subtract tiers. Or (for simplicity) just give them 5 tiers like in the DMG and let them pick the die formula for each. Preferably, the user could enter something like "2d6 - 1" for the die formula for a given level.

**Reason**
I think the DMG proficiency die is interesting, but mathematically I don't love it. At level 17, for example, a PC would have a +6 bonus or, under the alternative rule, roll a 1d12. That means, under the alternative, that the average bonus is 6.5 (which is basically the same) but the range is crazy-wide: +1 to a +12. I would prefer something that better approximates a normal bell curve, so that +6 is more likely than the extremes. This would make it much less likely that a high-level character totally botches a roll, and will make high-level characters more consistently perform better than low-level characters. 

To do that, I would change 1d12 to a 2d6. Similarly, I would change 1d8 to 2d4. Being that Foundry is a computer and not real life, I would probably also change 1d4 to 2d2 and 1d10 to 2d5. That would make the proficiency roll more likely to fall close to the expected proficiency bonus for the level.

In addition, to make the math work, I might add a minus 1. For example, 17th level would be 2d6 - 1, giving a range of 1 to 11, with mean 6. (The mean for 1d6 is 3.5, so doubling the dice would get to 7, then the -1 gets you back to 6.) Cuts off the top-end, but as a grumpy GM, not sure I want people running around with a potential +12 for proficiency.

**Comment by NekroDarkmoon** [comment]
Hmm, currently I'm just using math to calculate the prof die but yeah I can look into giving people the option of using different dies for each tier.
