### ISSUE TITLE
Flanking only works for the first attack

### ISSUE THREAD

**Issue by Avitale34** [NekroDarkmoon/optional-rules-dnd5e#14]
Hello I noticed that you need to retarget the target each time in order to get the flanking to automate. If you attack twice in a row only the first attack gets advantage.

**Comment by NekroDarkmoon** [comment]
I'll be able to take a look at this tomorrow.

**Comment by NekroDarkmoon** [comment]
I can't seem to be able to replicate that. 
![image](https://user-images.githubusercontent.com/49667684/126307549-77a86172-04d1-42ed-a1a0-a9481d311789.png)

**Comment by Avitale34** [comment]
Lol I can not reproduce now on my end either! Weird but thank you for checking!

**Comment by NekroDarkmoon** [comment]
No-problem.
