### ISSUE TITLE
[Bug] Expertise with tools

### ISSUE THREAD

**Issue by JavelinX** [NekroDarkmoon/optional-rules-dnd5e#17]
Hi NekroDarkmoon,

I noticed that the skill die for tools does not change no matter what skill level is chosen.

![image](https://user-images.githubusercontent.com/90550869/132981626-e288e976-8806-42b0-adb4-1f2d38530ca9.png)

Could you take a closer look?

Thank you very much for all your efforts.

Best regards, Jav

**Comment by NekroDarkmoon** [comment]
I won't be touching prof die for a bit because it's set to be included in the core 5e system
