### ISSUE TITLE
Question about Critical Hit and Fumble

### ISSUE THREAD

**Issue by marcstraube** [NekroDarkmoon/optional-rules-dnd5e#2]
Hi,
first off, thanks for fixing the install bug so fast!

I just tried the critical hit and fumble rule. I've created two roll tables and entered their names into the settings and enabled the rule. Then I rolled until I got a 1 and a 20, but nothing happened. No errors in the console.
Maybe some incompatible module settings?

Foundry: 0.8.6.
Midi-QOL: 0.8.10
LibWrapper: 1.6.2.0
Optional Rules for Dnd5e: 0.0.5

**Comment by NekroDarkmoon** [comment]
Sorry about that. It seems that when I integrated the proficiencyDie it somehow changed the function signature.

**Edit: Fixed**

**Comment by marcstraube** [comment]
Did a quick test - now it rolls a d6 after a critical or fumble, but its not rolling on the roll table. I'd yet have to test in a new world with all but the required modules disabled.

**Comment by NekroDarkmoon** [comment]
The roll on the d6 needs to be 5-6 to trigger the critical hit or fumble table roll. I plan to add the ability to change that threshold in the future.

**Comment by marcstraube** [comment]
This works! Thanks for your help!
