### ISSUE TITLE
Issue with saves/skills with Enable Proficiency Die Automation and Midi-QOL

### ISSUE THREAD

**Issue by Criilbilly** [NekroDarkmoon/optional-rules-dnd5e#26]
FoundryVTT version .8.9
D&D 5e version 1.5.2
Midi-QOL version .8.73
DAE .8.6
Optional Rules DnD5e version .2.8

Enabling the Proficiency Die Automation option causes all saving throws and skill checks to fail with the following errors:
Saving throws:
foundry.js:7896        
       Uncaught (in promise) Error: Unresolved StringTerm NaN requested for evaluation
[Detected 2 packages: system:dnd5e, midi-qol]
    at StringTerm.evaluate (foundry.js:7896)
    at D20Roll._evaluate (foundry.js:5487)
    at async d20Roll (systems/dnd5e/module/dice.js:252)
    at async Actor5e.rollAbilitySave (modules/midi-qol/src/module/patching.js:274)
 
Skill checks:
Uncaught (in promise) Error: Unresolved StringTerm [object Object] requested for evaluation
[Detected 2 packages: system:dnd5e, midi-qol]
    at StringTerm.evaluate (foundry.js:7896)
    at D20Roll._evaluate (foundry.js:5487)
    at async Module.d20Roll (dice.js:252)
    at async Actor5e.doRollSkill (patching.js:108)

I raised this with Midi-QOL and their response to raise the issue here:
"I've experimented a bit and it seems that it is an interaction between optional-rules-dnd5e and dae. The patching that optional-rules does in the case of DAE being installed is out of date. I think this requires an update to optional-rules-dnd5e.
Until then I suggest disabling the proficiency dice feature. I can't really make changes for otional-rules. Can you raise the problem on the optional-rules site?"

**Comment by NekroDarkmoon** [comment]
Proficiency die is now handled by the core dnd system. Disabling the proficiency die system in optional rules and enabling it in the core settings should fix the error. The prof die system will be removed from the module in the next update.
