### ISSUE TITLE
Flanking not working properly on version 0.4.0

### ISSUE THREAD

**Issue by swaggycodecat** [NekroDarkmoon/optional-rules-dnd5e#29]
Flanking on 0.4.0 does not work properly on a square grid with creatures larger than medium being targeted. It gives no message in chat or indication in the console that it's calculating anything, whereas it works immediately for medium creatures. I rolled back to version 0.3.1 and it works as expected. I spent some time looking through the code, but I'm not really sure why this is the case. Could have something to do with only checking the attacker's height instead of the target's height?

**Comment by NekroDarkmoon** [comment]
So, I've narrowed it down to the isAdjacent function. It'll take me a bit to solve it because the function is used in multiple places.

**Comment by NekroDarkmoon** [comment]
I've fixed the main issue, just going to make some more changes and alter the dependent functions accordingly. Should be fixed in next weeks update.

**Comment by NekroDarkmoon** [comment]
Should be fixed in the new release.
