### ISSUE TITLE
Hero Points assigning multiple d6's when subtracting below 1 under the max.

### ISSUE THREAD

**Issue by SkyRushSoul** [NekroDarkmoon/optional-rules-dnd5e#30]
Having a persistent issue where using Hero Points underneath the max -1 (i.e. anything below 5/6 or 8/9, etc.)

To illustrate, if the player modifies their resource from 5/6 to 4/6 it will roll 2d6 in the chat. From 1/6 to 0/6 it will roll 6d6 in the chat.

**Comment by NekroDarkmoon** [comment]
Thanks for the report. I'll try to fix it soon

**Comment by NekroDarkmoon** [comment]
Fixed in 0.5.0
