### ISSUE TITLE
Foundry v9.255 Flanking automation inoperable

### ISSUE THREAD

**Issue by TyphosTheD** [NekroDarkmoon/optional-rules-dnd5e#31]
I recently installed this module, the required libwrapper, and the More Hooks 5e module, enabled the flanking automation, but the automation does not seem to be functioning, among any creature type (NPC or PC) or size I use.

Perhaps I am trying to use it incorrectly, but I've been putting two tokens in flanking position another another, selecting a flanking token, then using Easy Target to target the middle token.

My understanding is that a prompt should appear in the chat box that flanking has been activated, but I've seen no such prompt.

**Comment by NekroDarkmoon** [comment]
I've just released an update for the module that fixed an issue with flanking. If it doesn't work double-check the settings to see if flanking is enabled.

**Comment by TyphosTheD** [comment]
So far no dice. Am I using the module correctly? I have the flanking feature enabled, select a token, then target another, while another token is on the opposite side.

Is there some function I need to enable to for it to recognize "allied" creatures adjacent?

**Comment by Dairid** [comment]
I am also having this same issue I can't seem to get it to work.  I use Midi-QOL and I messed with any settings there that i could think of.

**Comment by NekroDarkmoon** [comment]
Hmm, I'm not sure what could be causing that. Would it be possible to send a small gif of how you're going about flanking?

**Comment by Dairid** [comment]
![Flank issue](https://user-images.githubusercontent.com/99863119/159579270-97430f6d-b36f-4b94-887d-de1664076695.gif)

**Comment by Dairid** [comment]
quality isn't amazing but I also moved them around and I've tried just about every variant I can think of.  I also try with other enemies on allied pieces.  I have it set to just give a +2 bonus, but I also tried it without and still nothing.

**Comment by Dairid** [comment]
I also completely disabled Midi-QOL and it's dependencies.  It does not seem to be an issue with Midi.

**Comment by TyphosTheD** [comment]
I did some testing, too, here's my testing conditions, results, and associated gif I created.

Conditions:
- (3) Griffons, two hostile, one friendly
- (2) Firenewt Warriors, one hostile, one friendly
- (1) Animated Knife, hostile
- (5) PCs, all Friendly

https://user-images.githubusercontent.com/40187548/159586964-51889847-a76d-4de7-b730-bd8903579052.mp4

Results:
- Garik (Friendly PC) can flank the Hostile Firenewt with the Friendly Griffon, but the Friendly Griffon cannot flank the Hostile Firenewt back
- The Hostile Firenewt can Flank Javan (Friendly PC) with the Hostile Griffon, which can Flank in return, and the same Hostile Griffon can Flank Garik (Friendly PC) with the other Hostile Griffon, which can Flank in return.
- The Friendly Firenewt cannot Flank the Hostile Griffon with Javan (Friendly PC), nor in return.
- Vinny (Friendly PC) cannot Flank the Hostile Animated Knife with Caleris (Friendly PC).
- Javan (Friendly PC) cannot Flank the Hostile Firenewt with Delgrin (Friendly PC).

**Comment by Dairid** [comment]
Yeah I'm not even getting the chat output regardless of midi

**Comment by NekroDarkmoon** [comment]
hmm, that's super weird. I'll try replicating and either way push an update out with log outputs that people can report back

**Comment by NekroDarkmoon** [comment]
Sorry, it took me this long. I've been a bit busy with life and other stuff but I think I've potentially addressed this as well as added the debug logger.
