### ISSUE TITLE
[Bug] Uncaught ReferenceError + unused variable with flanking

### ISSUE THREAD

**Issue by Arcainne** [NekroDarkmoon/optional-rules-dnd5e#33]
I'm currently seeing this console error when trying to use flanking.
![image](https://user-images.githubusercontent.com/4230871/164610087-383c96ca-6d61-4d28-8fc7-8345b57e2c9e.png)

Looking at the code, it looks like the `index` variable is undefined (probably meant to use `i` instead). Also, the variable `effect` isn't used. The next line uses `effects` instead of `effect`.
https://github.com/NekroDarkmoon/optional-rules-dnd5e/blob/d8d6e83e76d23352b3c5c80631734a0420840ab4/modules/flanking.js#L320-L323

**Comment by NekroDarkmoon** [comment]
Fixed in 0.4.2

Thanks a lot <3
