### ISSUE TITLE
optional-rules settings without default value throw exception

### ISSUE THREAD

**Issue by wickermoon** [NekroDarkmoon/optional-rules-dnd5e#34]
Settings, like "optiona-rules-dnd5e.mainCritTable" lack a default value. When accessing those, foundry tries to get the setting via storage.getSetting(key). This returns undefined and it then tries to create a new Setting with the default value (that is undefined) and throws the following error

![image](https://user-images.githubusercontent.com/15907070/188304908-b909ca9d-fb2f-48d6-9410-bed013a2cf7c.png)

**Comment by NekroDarkmoon** [comment]
That deffo seems like a v10 compatibility error 🙃. I've started working on a v10 version so I'll pull your changes in with that. It might take a little bit longer since I'm gonna do a complete refactor of hero Points and flanking.

**Comment by wickermoon** [comment]
Oh, yeah, it totally is a v10 compat error, totally forgot to mention that! v10 enforces default values, but I guess it wouldn't hurt in v9 as well. Anyway, thanks for the consideration. Looking forward to the v10 release. :)

**Comment by NekroDarkmoon** [comment]
A v10 version has been released that should have fixed all of the issues.
