### ISSUE TITLE
Change the Threshold range.

### ISSUE THREAD

**Issue by marceloseara** [NekroDarkmoon/optional-rules-dnd5e#36]
Hi!

Could you consider changing the way the threshold works? Because now it's needed to result a value over the number, so if the threshold is 1, you roll the table with a result between 2 and 6, and with a threshold of 6 you never roll the table.
It will be more interesting if you roll when you take a value equal or over the threshold, so with a 1 you always roll at the table and with a 6 you roll only if you get a 6.

**Comment by NekroDarkmoon** [comment]
Apparently, someone forgot how maths works when they last made changes to the roll function 🤣. I'm surprised it took this long for this bug to be noticed. I'll fix it up in the next release. Thanks <3
