### ISSUE TITLE
[Bug] Flanking.

### ISSUE THREAD

**Issue by WiseWarrior** [NekroDarkmoon/optional-rules-dnd5e#37]
FoundryVTT v10, Build 288
optional-rules-dnd5e v0.5.0

When flanking one hostile token with another ally token, using the GM to select one ally token and targeting the hostile token, two chat cards are produced to declare the ally tokens are flanking a token.

Screenshot attached.

![image](https://user-images.githubusercontent.com/22104642/200216192-9f723272-ce03-4a05-9f4f-97846cb51c84.png)

Also, if I may add a request? Can you add an option to the module settings to disable this chat card entirely? To push my luck even further, another option to add a status icon to the flanked target would be ideal.

Thanks

**Comment by NekroDarkmoon** [comment]
I'm currently a little busy, but I'll take a look as soon as possible

**Comment by NekroDarkmoon** [comment]
So I've added the option to disable the chat card entirely. I'm not so sure about the status effect at the moment and would need to give it a bit more thought since it doesn't really convey the right information when placed on a target .
