### ISSUE TITLE
Dependency to More Hooks 5e

### ISSUE THREAD

**Issue by marcstraube** [NekroDarkmoon/optional-rules-dnd5e#41]
The More Hooks 5e repository has been archived and FoundryVTT version 9 is the last supported version. Will you integrate the Critical Hit and Fumble rules directly into your module so we can use it in v10?
Thanks a lot for your work!

**Comment by NekroDarkmoon** [comment]
It's something I've been planning on doing sometime this week.

**Comment by NekroDarkmoon** [comment]
Well, more to the fact to update the module for dnd 2.1.x. The dependency on more hooks 5e doesn't actually exist. I just need to take it out of the readme.
