### ISSUE TITLE
Module Shows in Other Systems

### ISSUE THREAD

**Issue by Vhostym-the-Sojourner** [NekroDarkmoon/optional-rules-dnd5e#42]
The module shows for other systems outside of 5e. Can the manifest be updated to be restricted to the compatible system?

Thanks!

Steps to Reproduce

    Go to Module Management in a non-5e system
    The module displays

Versions

    Module: [0.5.1]
    Foundry: [10.291]

**Comment by NekroDarkmoon** [comment]
Hmmm, I was pretty sure I'd already done that. I'll take a look and see what's up

**Comment by Intervencion** [comment]
https://github.com/NekroDarkmoon/optional-rules-dnd5e/pull/44
