### ISSUE TITLE
No settings appearing

### ISSUE THREAD

**Issue by Shayulghul** [NekroDarkmoon/optional-rules-dnd5e#43]
I don't seem to have any of the settings. I've tried in two 5e games (one is my test game). I was hoping to use the module for a fumble table, but I can't seem to get it to show the settings.

<img width="1079" alt="Screenshot 2023-07-04 at 6 46 54 PM" src="https://github.com/NekroDarkmoon/optional-rules-dnd5e/assets/81927456/3abe6473-2e7d-482e-bfc9-fc44fdea0d78">

Foundry v10.303
D&D5e v2.2.1
Chrome Version 114.0.5735.198

**Comment by NekroDarkmoon** [comment]
I'm a little bit busy but I'll see if I can try to get this fixed this coming week.
