### ISSUE TITLE
Flanking incorrectly applies to ranged attack rolls

### ISSUE THREAD

**Issue by nmchen** [NekroDarkmoon/optional-rules-dnd5e#7]
Currently it seems that Flanking applies to all attack rolls, not just melee attacks. (Tested with both weapon and spell ranged attacks.)

Excerpt from DMG for reference:
"When [...], they flank that enemy, and each of them has advantage on **melee** attack rolls against that enemy."

Currently managing it by just asking ranged attackers not to target, but it'd be nice to have it fixed for the games that use MidiQOL or other automations that require targeting.

**Comment by NekroDarkmoon** [comment]
It'll support that with the next update.

**Comment by NekroDarkmoon** [comment]
Implemented in 0.2.4.
