### ISSUE TITLE
Option to ignore flanking friendly and neutral creatures

### ISSUE THREAD

**Issue by apoapostolov** [NekroDarkmoon/optional-rules-dnd5e#8]
This should be optional as most DMs do not strictly edit the disposition of their tokens.

But it is very annoying when having players closer together, flanking is calculated against friendly creatures or allies and it is posted in the chat as clearly unless an exception players will never fight each other. 

The option when turned off checks the disposition and ignores flanking announcement (but can still silently calculate flanking) for friendly creatures. 

Also, I noticed that if a player does not target specifically an enemy, but is flanking a friendly creature, will still roll with advantage and has to ignore the second roll. Flanking automation should only apply when proper targeting is used.

**Comment by NekroDarkmoon** [comment]
Implemented in 0.2.4

**Comment by apoapostolov** [comment]
Thank you.
